project:
  type: website
  output-dir: docs

website:
  title: "Marissa Gill"
  navbar:
    logo: images/Marissa_Logo.png
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: education.qmd
        text: Education and Experience
      - href: whywater.qmd
        text: Why Water?

      

format:
  html:
    theme: 
    - style.css
    fontawesome: true
    css: styles.css
    toc: true

editor: visual

